# Додаткові завдання №3

## 1 Перевірка взаємної простоти двох чисел
Реалізуйте алгоритм Евкліда для перевірки взаємної простоти двох чисел (у вигляді функції від двох аргументів).
Виконайте друге завдання з **Домашньої роботи №3** (**Задача 1.3.14**) з використанням даної функції.

In [3]:
# Місце для Вашого коду
import numpy as np
from itertools import combinations


def is_mutually_simple(a, b):
    while a != 0 and b != 0:
        if a > b:
            a = a % b
        else:
            b = b % a
    return a + b == 1

def teor(n, k, p, q):
    amount = [0, 0, 0]
    count = 0
    for el in combinations(range(1, n+1), k):
        count += 1
        if all(map(lambda a: a % p == 0, el)):
            amount[0] += 1
        if all(map(lambda a: a % p == 0 or a % q == 0, el)):
            amount[1] += 1
        if any(map(lambda a: a % p == 0, el)):
            amount[2] += 1
    
    # just added the checking if p and q are mutually simple 
    if not is_mutually_simple(p, q):
        a[1] = None
    return list(map(lambda a: a / count, amount))


def practice(n, k, p, q):
    amount = [0, 0, 0]
    count = 0
    for _ in range(100000):
        el = np.random.choice(range(1, n+1), size=k, replace=False)
        count += 1
        if all(map(lambda a: a % p == 0, el)):
            amount[0] += 1
        if all(map(lambda a: a % p == 0 or a % q == 0, el)):
            amount[1] += 1
        if any(map(lambda a: a % p == 0, el)):
            amount[2] += 1
    
    # just added the checking if p and q are mutually simple 
    if not is_mutually_simple(p, q):
        a[1] = None
    return list(map(lambda a: a / count, amount))
    
    
for el in [(25, 5, 3, 4), (25, 10, 3, 4)]:
    print('teoretical for {}: {}'.format(el, teor(*el)))
    print('empirical for {}: {}'.format(el, practice(*el)))


teoretical for (25, 5, 3, 4): [0.001054018445322793, 0.014906832298136646, 0.8835309617918313]
empirical for (25, 5, 3, 4): [0.00116, 0.01466, 0.88373]
teoretical for (25, 10, 3, 4): [0.0, 2.0191142818683536e-05, 0.9940503432494279]
empirical for (25, 10, 3, 4): [0.0, 2e-05, 0.99402]


## 2 Аналіз функцій з класу *numpy.random*
Проаналізуйте взаємозв'язок між функціями з класу **numpy.random**:
- [rand](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.rand.html)
- [randint](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.randint.html)
- [random_integers](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.random_integers.html)
- [random_sample](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.random_sample.html)
- [random](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.random.html)
- [ranf](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.ranf.html)
- [sample](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.sample.html)
- [choice](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.choice.html)
- [shuffle](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.shuffle.html)
- [permutation](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.permutation.html)

In [18]:
# Місце для Вашого коду та висновків

# однакові функції, в яких тільки відрізняється вигляд параметра size
# зроблено для зручності
print(np.random.rand(3, 2), '\n')
print(np.random.random_sample((3, 2)), '\n')

# в цих функціях документація з random_sample. Скоріш за все, теж зроблено для зручності
print(np.random.random((3, 2)), '\n')
print(np.random.ranf((3, 2)), '\n')
print(np.random.sample((3, 2)), '\n')

# randint(low, hight, size, dtype) генерує випадкове число (або size чисел) з рівномірним дискретним розподілом з 
# напівінтервала [low, hight)
# якщо hight упущений, то з напівінтервала [0, low)
# dtype додатково вказує якого типу буде вертатись результат

# random_integers(low, hight, size) генерує випадкове число (або size чисел) з рівномірним дискретним розподілом з 
# відрізка [low, hight]
# якщо hight упущений, то з відрізка [1, low]

print(np.random.randint(1, 15, size=50), '\n')
print(np.random.random_integers(1, 15, size=50), '\n')


# shuffle перемішує список/масив, а permutations створює копію списку/масиву і перемішує її
a = np.arange(1, 100)
print('a: ', a, '\n')
print('permutation: ', np.random.permutation(a), '\n')
print("a didn't change:", a, '\n')
np.random.shuffle(a)
print("after shuffle:", a, '\n')


[[0.99861022 0.32528565]
 [0.30015375 0.5565446 ]
 [0.42238089 0.38611374]] 

[[6.61055504e-01 9.10716335e-01]
 [8.07047201e-01 5.88175299e-04]
 [8.87927326e-01 3.22498318e-01]] 

[[0.73459701 0.05886384]
 [0.92837092 0.85335752]
 [0.75964818 0.38446405]] 

[[0.99487005 0.66068076]
 [0.3442691  0.68640326]
 [0.7922874  0.73994385]] 

[[0.41093755 0.83057912]
 [0.91405073 0.35390571]
 [0.06484533 0.2782682 ]] 

[ 7  9 12 10  3  5  7  9  3 11  2  9  1  2 13 14  3 12  6  4  4 11  6  2
 14 13  2 12 14 10 12 12  6  3  8  8  4  1  9 11  1  1  3 11  3 11  8  6
 12 14] 

[ 1  6  4 13  6 11 14 12  7  1 12  1 14  9  5  6 12  8  7 14  2  4 15  7
 10 11  5 14  6 10 10  9  5  5  2  5  8 12  9 11 14 13  4  5 13  2  4  4
 10  2] 

a:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89

/usr/lib/python3/dist-packages/ipykernel_launcher.py:23: DeprecationWarning: This function is deprecated. Please call randint(1, 15 + 1) instead
